apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-api
      annotations:
        checksum/config: {{ print .Values.api.config | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.api.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.api.service.internalPort }}
          initialDelaySeconds: 60
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.api.service.internalPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
          - name: config
            mountPath: /root/monocular/config
        resources:
{{ toYaml .Values.api.resources | indent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-api-config
