version: '2'

services:
  ui:
    tty: true # Enables debugging capabilities when attached to this container.
    build: ./dev_env/ui
    ports:
      - 4200:4200
    volumes:
      - ./src/ui:/app
    command: "ng serve --host 0.0.0.0 --proxy-config proxy.conf.json"
  api:
    tty: true
    build: ./dev_env/api
    volumes:
      - ./src/api:/go/src/github.com/kubernetes-helm/monocular/src/api
      # Config example file
      - ./docs/config.example.yaml:/root/monocular/config/monocular.yaml
      # Used for loading kubernetes context used on Helm releases integration
      - $HOME/.kube/:/root/.kube
    environment:
      - ENVIRONMENT=development
  mongodb:
    image: bitnami/mongodb:3
