apiVersion: v1
name: monocular
description: Monocular is a search and discovery front end for Helm Charts Repositories.
version: 1.4.7
appVersion: v1.8.0
home: https://github.com/helm/monocular
sources:
- https://github.com/helm/monocular
maintainers:
- name: prydonius
  email: adnan@bitnami.com
